### ISSUE TITLE
easyconfig  prędkość

### ISSUE THREAD

**Issue by szwagierluki** [obsy/packages#10]
Czy dałoby radę zrobić prędkość jaki wchodzi i wychodzi z wan ?

**Comment by obsy** [comment]
Chyba tak, tylko muszę znaleźć coś małego co będzie sobie biegało w tle i liczyło te bajty.

**Comment by obsy** [comment]
Wystarczy że otworzy się okienko i zacznie się wyświetlać prędkość up/down w KiB/s MiB/s itd?

**Comment by szwagierluki** [comment]
Dzięki :)

**Comment by obsy** [comment]
Tak, wiem, tam aż się prosi żeby zrobić wykres bandwidth. Ale nie znalazłem żadnej małej biblioteki która by to umożliwiała, więc chyba po prostu będę musiał sobie taki graf napisać tak jak to dla wifi zrobiłem. Wylądowało to na liście todo, ale głęboko zakopane :)
