### ISSUE TITLE
easyconfig sieci wifi

### ISSUE THREAD

**Issue by szwagierluki** [obsy/packages#11]
Dałoby radę oddzielić wifi 2.4 od 5? Ogólnie ok ale jak ktoś mieszka w bloku strasznie pomieszane

**Comment by obsy** [comment]
Piszesz o zakładce statusu, tak?

**Comment by szwagierluki** [comment]
Zakładka sieci wifi a tam lista wszystkich znalezionych sieci 2.4 i 5 w jednym. Wiem można posortwać po kanale, ale dalej pomieszane ;)

**Comment by obsy** [comment]
Mogę to jakąś kreską oddzielić, ale na razie średnio mi się to podoba.

**Comment by szwagierluki** [comment]
ok :)

**Comment by obsy** [comment]
![a](https://user-images.githubusercontent.com/695356/73017844-c3054700-3e20-11ea-8a39-7134f1fd9bc9.png)
Coś takiego wymyśliłem. Jak się okaże że nic nie zepsułem to coś podobnego umieszczę w repo.

**Comment by szwagierluki** [comment]
mhm ładnie :)

**Comment by obsy** [comment]
Dodałem.
