### ISSUE TITLE
sugestie

### ISSUE THREAD

**Issue by szwagierluki** [obsy/packages#4]
1.Czy byłaby możliwość dodania automatycznego odświeżania strony?
2.Dodanie daty i czasu ?
3.Zakładka "transfer" dane dziś/wczoraj/.. są sumą wysłaną i pobraną a nie można by rozgraniczyć na dane wysłane dane pobrane

**Comment by obsy** [comment]
Ale to są sugestie do czego? easyconfig?

**Comment by szwagierluki** [comment]
tak :)

**Comment by obsy** [comment]
1. Statusu tak. Reszty unikałbym, bo podciąganie danych zajmuje chwilę.
2. Tak, bez problemu. Ale jak wiadomo router nie ma RTC, więc jak ktoś wczyta stronę zanim pojawi się wan i zsynchronizuje czas to będzie widział go z przeszłości. Chyba że go nie pokazywać dopóki nie będzie zsynchronizowany
3. Tak, choć specjalnie na początku zrobiłem to jako sumę właśnie...

**Comment by szwagierluki** [comment]
ooo to super dokładnie chodzi mi o sam status
btw. planujesz jeszcze zakładkę firewall ?

**Comment by obsy** [comment]
Nie, ponieważ zbytnio nie mam co w niej pokazywać :)

**Comment by szwagierluki** [comment]
Nie lepszym rozwiązaniem byłoby aby przycisk menu był w stałej pozycji podczas scrollowania ?

**Comment by obsy** [comment]
Nie wiem, o przycisku menu nie myślałem w ten sposób. Bardziej by mi się przydał pływający przycisk "odśwież".

**Comment by szwagierluki** [comment]
Zakładka 'Transfer' dane są pokazywane 1,2,3...TB a może tak bardziej szczegółowo np z dwoma miejscami po przecinku ?;)

**Comment by obsy** [comment]
Serio udało Ci się przewalić TB danych?

**Comment by szwagierluki** [comment]
tak wan

**Comment by obsy** [comment]
![a](https://user-images.githubusercontent.com/695356/32671077-50010f36-c646-11e7-83ea-b3a3b493c23c.png)

KB/MB wyświetlają się w zaokrągleniu, GB i TB do trzech miejsc po przecinku. Może być?

**Comment by szwagierluki** [comment]
Tak tak...:)

**Comment by szwagierluki** [comment]
wg konsoli up 10 days,  9:17 wg web Czas pracy 19h 17m

**Comment by obsy** [comment]
Pokaż wyniki poleceń:
cat /proc/uptime
ubus call easyconfig status

**Comment by szwagierluki** [comment]
897819.27 796240.90
{
        "system_uptime": "19h 23m",
        "system_load": "2.03 2.38 1.38",
        "system_time": "2017-11-10 19:46",
        "wlan_clients": "2",
        "wan_rx": "247.7 GiB",
        "wan_tx": "689.6 GiB",
        "wan_since": "2017-11-10 17:06",
        "wan_uptime": "2h 40m",
        "wan_up_cnt": "1",
        "version": "LEDE Reboot 17.01-SNAPSHOT r3566-98c003e",
        "gui_version": "-devel-",
        "model": "NETGEAR WNDR4300"
}

**Comment by obsy** [comment]
To dlatego że uptime 10dni masz :) poprawiłem, dzięki.

**Comment by szwagierluki** [comment]
Teraz mam
Status:
Wysłano
741119149579
Pobrano
266062659988
Transfer:
Dziś
149 GiB 

Wczoraj
79 GiB

Ostatnie 7 dni
620 GiB

Ostatnie 30 dni
1 TiB

Łącznie
2 TiB (od 2017-10-25)

Bieżący okres rozliczeniowy
924 GiB 

Poprzedni okres rozliczeniowy
755 GiB

**Comment by obsy** [comment]
Za mało rzeczy aktualizowałeś albo wyczyść cache przeglądarki.

**Comment by szwagierluki** [comment]
yhy shift F5 pomogło... :))
Teraz dla mnie super dzięki

**Comment by szwagierluki** [comment]
Fajnie że rozdzieliłeś transfer :) i teraz:
1.Pozostanie tylko rozdzielone "dziś" czy polecisz dalej ?
2.Może wektory w kolorze ?

**Comment by obsy** [comment]
Dnia 2018-04-01, o godz. 04:56:30
szwagierluki <notifications@github.com> napisał(a):

> Fajnie że rozdzieliłeś transfer :) i teraz:
> 1.Pozostanie tylko rozdzielone "dziś" czy polecisz dalej ?

Oczywiście z rozdzieleniem pozostałych rzeczy nie ma problemu, bo dane
są, ale... wygląda to beznadziejnie w gui, bo pojawi się duża lista 
liczb i jest to mało czytelne. Zresztą prezentacja tego przy "dziś"
też mi średnio leży, to co wysłałem do repo jest już Ntym podejściem
do tematu.
Tak więc - na razie stwierdziłem że zostaje tylko "dziś". 

> 2.Może wektory w kolorze ?

Czerwony używam do ostrzeżeń, niebieski do linków. Kolorem raczej nie,
może boldem to strzelić żeby były bardziej czytelne.


-- 
Pozdrawiam,
 Cezary Jackiewicz

**Comment by szwagierluki** [comment]
Mało czytelne faktycznie... a rozwijane "dziś" a w nim rx/tx ...klikasz i masz piękne cyferki ;)

**Comment by obsy** [comment]
Zamieniłem to na klikany link z okienkiem ze szczegółami.

**Comment by szwagierluki** [comment]
aktualne devel
zakładka "system" i wyświetla "brak pobierania danych"

**Comment by obsy** [comment]
/usr/libexec/rpcd/easyconfig nie zaktualizowałeś lub nie zrestartowałeś rpcd po podmianie.

**Comment by szwagierluki** [comment]
Planujesz pppoe?

**Comment by obsy** [comment]
A używasz? Bo ja nie i nie mam na czym testować. Mogę dołożyć jako opcję konfiguracyją.

**Comment by szwagierluki** [comment]
Tak używam pppoe-wan

**Comment by obsy** [comment]
Jaki masz konfig?
option ifname...
opton username ...
option passwordd ..
option proto pppoe

i to tyle czy coś jeszcze?

**Comment by szwagierluki** [comment]
config interface 'wan'
	option proto 'pppoe'
	option ipv6 '0'
	option password 'xxx'
	option username 'xxx'
	option peerdns '0'
	list dns 'xxx'
	option keepalive '0'
	option ifname 'eth0.35'

**Comment by obsy** [comment]
A to nie, tak szybko tego nie będzie. Używasz vlana, co komplikuje sposób jego tworzenia na różnych routerach.

**Comment by szwagierluki** [comment]
Tak światlo od pomarańczy + ONT
