### ISSUE TITLE
Daemon monitor for signal\sms\voice calls

### ISSUE THREAD

**Issue by alex-eri** [obsy/packages#6]
Modern modems has separate port for UI. We can write deamon that monitors this port for real time signal level and sms. Like ModemManager. Polling is too slow.

I did not found project for this scenario. Except ModemManager, but it is massive for routers. New one needed!  But it is difficult to code alone.

**Comment by obsy** [comment]
You can use ugps as the base of code. It  takes messages and parse it, so change  to parse  ^DSFLOWQRY, ^RSSI, ^MODE, depending on modem model.
