### ISSUE TITLE
wan rx/tx

### ISSUE THREAD

**Issue by szwagierluki** [obsy/packages#7]
Po wczorajszej aktualizacji:
status >> wysłano/pobrano NaN undefined
transfer >> dziś 0

**Comment by obsy** [comment]
Pokaż wyniki:
```
ubus call easyconfig status
ifconfig
uci show network
```

**Comment by szwagierluki** [comment]
ubus call easyconfig status
{
        "system_uptime_since": "2018-02-10 19:36",
        "system_uptime": "1886932",
        "system_load": "0.08 0.02 0.00",
        "system_time": "2018-03-04 15:45",
        "wlan_clients": "0",
        "wan_rx": "0 854080346457",
        "wan_tx": "0 1557116479481",
        "wan_uptime_since": "2018-02-10 19:37",
        "wan_uptime": "1886902",
        "wan_up_cnt": "1",
        "wan_ipaddr": "xxx",
        "version": "LEDE Reboot 17.01-SNAPSHOT r3825-28483d4",
        "gui_version": "-devel-",
        "model": "NETGEAR WNDR4300"

ifconfig
br-lan    Link encap:Ethernet  HWaddr A0:63
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1367861959 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1179446480 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1550610579024 (1.4 TiB)  TX bytes:870385364239 (810.6 GiB)

eth0      Link encap:Ethernet  HWaddr 1A:23
          inet6 addr: fe80::1823:63ff:fe82:6235/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2553258578 errors:0 dropped:0 overruns:1173 frame:0
          TX packets:2527986643 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2356693259 (2.1 GiB)  TX bytes:88895665 (84.7 MiB)
          Interrupt:4

eth0.1    Link encap:Ethernet  HWaddr A0:63
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1373436573 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1171450409 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1559037996406 (1.4 TiB)  TX bytes:868090206645 (808.4 GiB)

eth0.2    Link encap:Ethernet  HWaddr A0:63
          inet addr:xxx  Bcast:xxx  Mask:255.255.255.224
          inet6 addr: fe80::a263:91ff:fe7d:314/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:1179821961 errors:0 dropped:187567 overruns:0 frame:0
          TX packets:1356558392 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:854081328898 (795.4 GiB)  TX bytes:1557165852473 (1.4 TiB)

ifb0      Link encap:Ethernet  HWaddr 4E:89
          inet6 addr: fe80::4c89:ebff:fe47:a284/64 Scope:Link
          UP BROADCAST RUNNING NOARP  MTU:1500  Metric:1
          RX packets:744147777 errors:0 dropped:0 overruns:0 frame:0
          TX packets:744147777 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:32
          RX bytes:552237499608 (514.3 GiB)  TX bytes:552237499608 (514.3 GiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:130793 errors:0 dropped:0 overruns:0 frame:0
          TX packets:130793 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:11531889 (10.9 MiB)  TX bytes:11531889 (10.9 MiB)

wlan0     Link encap:Ethernet  HWaddr A0:63
          inet6 addr: fe80::a263:91ff:fe7d:313/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:592910 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1478567 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:80495245 (76.7 MiB)  TX bytes:1842851250 (1.7 GiB)

wlan1     Link encap:Ethernet  HWaddr A0:63
          inet6 addr: fe80::a263:91ff:fe7d:315/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:337 errors:0 dropped:0 overruns:0 frame:0
          TX packets:64437 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:67113 (65.5 KiB)  TX bytes:8584558 (8.1 MiB)



uci show network
network.loopback=interface
network.loopback.ifname='lo'
network.loopback.proto='static'
network.loopback.ipaddr='127.0.0.1'
network.loopback.netmask='255.0.0.0'
network.loopback.ipv6='0'
network.globals=globals
network.lan=interface
network.lan.type='bridge'
network.lan.ifname='eth0.1'
network.lan.proto='static'
network.lan.ipaddr='192.168.1.1'
network.lan.netmask='255.255.255.0'
network.lan.delegate='0'
network.lan.ipv6='0'
network.lan_dev=device
network.lan_dev.name='eth0.1'
network.lan_dev.macaddr='a0:63'
network.wan_dev=device
network.wan_dev.name='eth0.2'
network.wan_dev.macaddr='a0:63'
network.wan6=interface
network.wan6.ifname='eth0.2'
network.wan6.proto='dhcpv6'
network.wan6.reqaddress='none'
network.wan6.reqprefix='no'
network.wan6.delegate='0'
network.wan6.ipv6='0'
network.@switch[0]=switch
network.@switch[0].name='switch0'
network.@switch[0].reset='1'
network.@switch[0].enable_vlan='1'
network.@switch_vlan[0]=switch_vlan
network.@switch_vlan[0].device='switch0'
network.@switch_vlan[0].vlan='1'
network.@switch_vlan[0].ports='1 2 3 4 0t'
network.@switch_vlan[1]=switch_vlan
network.@switch_vlan[1].device='switch0'
network.@switch_vlan[1].vlan='2'
network.@switch_vlan[1].ports='5 0t'
network.wan=interface
network.wan.delegate='0'
network.wan.ifname='eth0.2'
network.wan.proto='dhcp'

**Comment by obsy** [comment]
Nie, to nie wczorajsza aktualizacją. Problemem jest:
```
"wan_rx": "0 854080346457",
"wan_tx": "0 1557116479481",
```
Oczywiście. Pokaż  jeszcze
```
ubus call network.interface.wan status
cat /proc/net/dev
```

**Comment by szwagierluki** [comment]
ubus call network.interface.wan status
{
        "up": true,
        "pending": false,
        "available": true,
        "autostart": true,
        "dynamic": false,
        "uptime": 1887569,
        "l3_device": "eth0.2",
        "proto": "dhcp",
        "device": "eth0.2",
        "metric": 0,
        "dns_metric": 0,
        "delegation": false,
        "ipv4-address": [
                {
                        "address": "xxx",
                        "mask": 27
                }
        ],
        "ipv6-address": [

        ],
        "ipv6-prefix": [

        ],
        "ipv6-prefix-assignment": [

        ],
        "route": [
                {
                        "target": "x0x",
                        "mask": 32,
                        "nexthop": "0.0.0.0",
                        "source": "xxx\/32"
                },
                {
                        "target": "0.0.0.0",
                        "mask": 0,
                        "nexthop": "x0x",
                        "source": "xxx\/32"
                }
        ],
        "dns-server": [
                "x00x",
                "8.8.8.8"
        ],
        "dns-search": [
                "xxx.pl"
        ],
        "inactive": {
                "ipv4-address": [

                ],
                "ipv6-address": [

                ],
                "route": [

                ],
                "dns-server": [

                ],
                "dns-search": [

                ]
        },
        "data": {
                "leasetime": 216000
        }
}


 cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  ifb0: 552237499608 744147777    0    0    0     0          0         0 552237499608 744147777    0    0    0     0       0          0
eth0.1: 1559995541030 1374107381    0    0    0     0          0    162875 868116570878 1171774185    0    0    0     0       0          0
    lo: 11532653  130797    0    0    0     0          0         0 11532653  130797    0    0    0     0       0          0
 wlan1:   67113     337    0    0    0     0          0         0  8639557   64813    0    0    0     0       0          0
 wlan0: 80495245  592910    0    0    0     0          0         0 1842906249 1478943    0    0    0     0       0          0
  eth0: 3353995459 2554252146    0    0 1173     0          0         0 1085940443 2528979593    0    0    0     0       0          0
ifb4eth0:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
ifb4eth0.2:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
br-lan: 1551568123648 1368532767    0    0    0     0          0         0 870411728472 1179770256    0    0    0     0       0          0
eth0.2: 854103202250 1180144721    0 187640    0     0          0    608940 1558132561218 1357227566    0    0    0     0       0          0

**Comment by obsy** [comment]
"Poprawione" w https://github.com/obsy/packages/commit/808e0935b83281bd7159d2def93d894d58d86d6a#diff-7562dea61a5b51d92423e144de1e118a

Problem u Ciebie było istnienie interfejsu (ifb4eth0.2) który miał w nazwie to samo co interfejs wan (eth0.2). Sprawdzałem, czyta teraz poprawnie. Sprawdź u sobie czy jest ok.

**Comment by szwagierluki** [comment]
Tak,Tak działa...
Dzięki ;)

**Comment by obsy** [comment]
I jeszcze: https://github.com/obsy/packages/commit/e43f6c461a8608afbb902340a8603fd71e13f975

**Comment by szwagierluki** [comment]
Status pokazuje dobrze natomiast transfer &#34;Dziś&#34; pokazuje dalej 0 
                
              
               
                 
                  Dnia 4 marca 2018 16:17 Cezary Jackiewicz &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   I jeszcze:  github.com e43f6c4

**Comment by obsy** [comment]
To ostatnie jeszcze zmień. Ew zobacz co masz w /tmp/easyconfig_traffic.txt, ma być tylko jedna linia z bieżącą datą i danymi, bez enterów itd.

**Comment by szwagierluki** [comment]
okej działa dzięki :)) 
                
              
               
                 
                  Dnia 4 marca 2018 16:27 Cezary Jackiewicz &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   To ostatnie jeszcze zmień. Ew zobacz co masz w /tmp/easyconfig_traffic.txt, ma być tylko jedna linia z bieżącą datą i danymi, bez enterów itd.
