### ISSUE TITLE
easyconfig Emoji

### ISSUE THREAD

**Issue by szwagierluki** [obsy/packages#9]
OpenWrt SNAPSHOT w zakładce "sieci wifi" ssid pokazuje krzaczki, a w zakładce "system" jest dobrze.
Na ostatnim Twoim lede pokazuje emoji normalnie.

**Comment by obsy** [comment]
Tak, ponieważ narzędzie iw które jest w openwrt nie wyświetla znaków innych niż z te zwykłe. W lede miałem małą poprawkę które to robiła (mogąca spowodować jakieś szopki jak by coś w nazwie ssid było), do openwrt 18.06 tego nie przenosiłem.

**Comment by obsy** [comment]
Lepiej późno niż wcale - dodałem programowe dekodowanie krzaczków utf-8 ( https://github.com/obsy/packages/commit/12a98330d8bd3dd725f6beb50522c0326699f2ba ) więc emoji normalnie się wyświetla (tak samo jak np. polskie litery).
